[package]
name = "homepage-nix"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.1"
actix-files = "0.6.5"
clap = "3"

[dev-dependencies]
actix-rt = "2.9.0"
bytes = "1.5.0"

